name: Docker Push

on:
  push:
    branches:
      - master

jobs:
  build-train:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile-train --tag contextualist/deepspeech:train-latest

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push image
        run: docker push contextualist/deepspeech:train-latest

      - name: Logout
        run: docker logout
